#!/bin/bash 

#This function creates parcellates superficial white matter (SWM) ROIs
#requires FSL

usage() {
echo ""
echo "Usage: create_regional_atlas SWM_mask 4D_GM_atlas SWM_atlas <sigma>"
echo "NOTE: SWM_mask and 4D atlas file should be in the same space" 
echo ""
exit 1
}
[ "$3" = "" ] && usage

if [ $4 = ""]
then
sigma=5
else
sigma=$4
fi

fslmaths  $1 -sub $1 zero
fslmerge -t tmp_swm_4D zero $2
fslmaths tmp_swm_4D -mul 100 -s $sigma tmp_swm_smooth 
fslmaths tmp_swm_smooth -Tmaxn tmp_swm_maxn
fslmaths tmp_swm_maxn -mul $1 $3
rm tmp_swm*gz

