#!/bin/bash 
#Prints out average values from each ROI from the given atlas (comma delimited)

#Arash Nazeri, Kimel Family Translational Imaging-Genetics Research Lab

#Developed at Kimel Family Translational Imaging Genetics Ressearch
#Laboratory (TIGR), Research Imaging Centre, Campbell Family Mental
#Health Institute,Centre for Addiction and Mental Health (CAMH), 
#Toronto, ON, Canada
# http://imaging-genetics.camh.ca


#requires FSL
#Example:
#./SWM_stats SWM_atlas input_image
#Input image could be a diffusion metric image

usage() {
echo ""
echo "Usage: SWM_stats SWM_atlas.nii.gz input_image.nii.gz [mask.nii.gz]"
echo "NOTE: SWM_mask and 4D atlas file should be in the same space" 
echo ""
exit 1
}
[ "$2" = "" ] && usage

if [ ! $3 = "" ]
then
fslmaths $1 -mul $3 tmp_swm_mask
else
fslmaths $1 tmp_swm_mask
fi

end=`fslstats $1 -R|awk '{print $2}'`
end=${end%.*}

i=1
while [ "$i" -le "$end" ]; do
  i=$(($i + 1))
  
min=`echo "$i-0.5"|bc`
max=`echo "$i+0.5"|bc`
ind=`echo "$i-1"|bc`

fslmaths tmp_swm_mask -thr $min -uthr $max -bin mask
output[$ind]=`fslstats $2 -k mask -M`
  
done
echo "${2} ${output[*]}"
