#!/bin/bash 
#Prints out average values from each ROI from the given atlas (comma delimited)

#Arash Nazeri, Kimel Family Translational Imaging-Genetics Research Lab

#Developed at Kimel Family Translational Imaging Genetics Ressearch
#Laboratory (TIGR), Research Imaging Centre, Campbell Family Mental
#Health Institute,Centre for Addiction and Mental Health (CAMH), 
#Toronto, ON, Canada
# http://imaging-genetics.camh.ca


#requires FSL
#Example:
#./SWM_stats SWM_atlas input_image


usage() {
echo ""
echo "Usage: create_regional_atlas SWM_mask 4D_GM_atlas SWM_atlas <sigma>"
echo "NOTE: SWM_mask and 4D atlas file should be in the same space" 
echo ""
exit 1
}
[ "$3" = "" ] && usage


